version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
